### PR TITLE
Add Custom Gradient Editor

### PR DESCRIPTION
**Pull request by DrOverbuild**
I'm a huge fan of this project, and I wanted to contribute a little feature that I have found useful, and I'm sure many others will too. 

This PR implements functionality to create new gradients for the analyzer.

For an overview of what this feature looks like, I have prepared a [short video](https://www.youtube.com/watch?v=qlDNLSrTvl8).

* Added an "Add Gradient" button under the enabled gradients list in the config panel. When clicked, it populates the gradient editor with a new gradient and opens the editor panel.
* Added a new modal window with UI controls for editing gradients.
  * The name field offers a public facing name for the gradient.
  * The colors table allows the user to add as many color stops as needed. Each row has:
    * A color input, for using a color picker to select the color.
    * A text input to set the hex color value.
    * A position field to adjust the color stop position.
    * An "add gradient" button. When clicked, a new color stop is added to the `currentGradient` object, and the colors table is rerendered. The position is automatically determined from the midpoint between its previous color stop and the next color stop.
    * A "remove gradient" button that removes the color stop from the `currentGradient` object and rerenders the colors table. If there are only two colors in the gradient, this button is disabled.
  * A checkbox to allow the gradient to show horizontally.
  * A color picker to adjust the background color.
* Custom gradients are added to the enabled gradients list. When a custom gradient in that list is clicked, the gradient editor is populated with a clone of the selected gradient for editing.
* When the save button is clicked in the gradient editor:
  * The saved gradient is assigned to the global `gradients` object. If the gradient is a new gradient, the key is generated uniquely. If the gradient is being edited, we keep track of the key in the `currentGradient` object and the gradient in the global `gradients` object is overwritten.
  * The gradient combo box in the settings panel is repopulated.
  * The enabled gradients list in the config panel is repopulated.
  * The gradient is registered to the analyzer.
  * Custom gradients are saved to local storage to be loaded across sessions.
* If the gradient editor has loaded an existing gradient, a delete button is available. When clicked:
  * The gradient is removed from the global `gradients` object.
  * The gradient combo box is repopulated.
  * The enabled gradients list is repopulated.
  * If the deleted gradient is the only enabled gradient, we automatically select the first gradient in the `gradients` object to be enabled.
  * The custom gradients are updated in local storage.

While initially I worked on these features from the `master` branch, I noticed progress coming from `dev`, so I've also updated `dev` if you'd rather me submit a PR for that. Apart from a few conflicts that I've fixed, everything is working smoothly in `dev`

### CODE REVIEW

**Comment by hvianna** [comment]
Wow! Thanks @DrOverbuild, this looks fantastic!! 🤩
Could you please resubmit this against the `dev` branch? I'm working on an update and I just pushed some more changes to that branch.
I really want to release the new version ASAP to celebrate audioMotion's third anniversary, and it would be great to include your gradient editor as well! 🚀

**Comment by hvianna** [comment]
I'd suggest adding an "offset" label for the colorstops offsets. What do you think?
image

**Comment by DrOverbuild** [comment]
> I'd suggest adding an "offset" label for the colorstops offsets. What do you think?
> image

I think that is a good idea. I will update with those changes and submit to `dev`

**Comment by DrOverbuild** [comment]
Closed because #26 merges into `dev`

**Pull request closed without merging**
